services:
  #database section
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - "1435:1433"
  productdb:
    image: mysql:8.0.29
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  customerdb:
    image: postgres:alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "3308:5432"
  basketdb:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  inventorydb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  #infrastructure
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  portainer:
    image: portainer/portainer-ce
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  #microservices api section
  product-api:
    image: ${DOCKER_REGISTRY-}product-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Product.API/Dockerfile
   
networks:
  default:
    name: emicroservices_v2
    driver: bridge
volumes:
  sqlserver_data:
    name: sqlserver_data
  mysql_data:
    name: mysql_data
  postgres_data:
    name: postgres_data
  redis_data:
    name: redis_data
  mongo_data:
    name: mongo_data
  portainer_data:
    name: portainer_data
  elasticsearch_data:
    name: elasticsearch_data
  jaeger_data:
    name: jaeger_data
  pgadmin_data:
    name: pgadmin_data