services:
  #database section
  orderdb:
    container_name: orderdb_eshop_micr
    environment:
      SA_PASSWORD: "Admin@1234"
      ACCEPT_EULA: "Y"
    restart: always

  productdb:
    container_name: productdb_eshop_micr
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    restart: always

  customerdb:
    container_name: customerdb_eshop_micr
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: CustomerDB
    restart: always

  basketdb:
    container_name: basketdb_eshop_micr
    restart: always

  inventorydb:
    container_name: inventorydb_eshop_micr
    restart: always

  #infrastructure section
  rabbitmq:
    container_name: rabbitmq_eshop_micr
    restart: always

  pgadmin:
    container_name: pgadmin_eshop_micr
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always

  portainer:
    container_name: portainer_eshop_micr
    restart: always

  elasticsearch:
    container_name: elasticsearch_eshop_micr
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    container_name: kibana_eshop_micr
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  #microservices section
  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:ProductConnection=Server=productdb;Port=3306;Database=ProductDB;User Id=root;Password=123456;"
    depends_on:
      productdb:
        condition: service_healthy
    ports:
      - "6002:80"
    restart: always

  customer.api:
    container_name: customer.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:CustomerConnection=Server=customerdb;Port=5432;Database=CustomerDB;User Id=admin;Password=123456;"
    depends_on:
      customerdb:
        condition: service_healthy
    ports:
      - "6003:80"
    restart: always

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      basketdb:
        condition: service_healthy
    ports:
      - "6004:80"
    restart: always