version: '3.8'

services:
  #database section    
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

#network section
networks:
  default:
    name: eShopMicroservices
    driver: bridge

#volumns section
volumes:
  sqlserver_data:
   name: sqlserver_data  
  